pub const DEVICE_OWNER_AUTHENTICATION_WITH_BIOMETRICS: i32 = 1;
pub const DEVICE_OWNER_AUTHENTICATION: i32 = 2;
pub const DEVICE_OWNER_AUTHENTICATION_WITH_WATCH: i32 = 3;
pub const DEVICE_OWNER_AUTHENTICATION_WITH_BIOMETRICS_OR_WATCH: i32 = 4;
pub const DEVICE_OWNER_AUTHENTICATION_WITH_COMPANION: i32 = 3;
pub const DEVICE_OWNER_AUTHENTICATION_WITH_BIOMETRICS_OR_COMPANION: i32 = 4;
pub const DEVICE_OWNER_AUTHENTICATION_WITH_WRIST_DETECTION: i32 = 5;
